### Blogs get request
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
  "title": "first post",
  "author": "tej",
  "url": "blog/1",
  "likes": "100"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
  "title": "second post",
  "author": "tejred",
  "url": "blog/2"
}


###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
  "title": "second post",
  "author": "tejred"
}

###
DELETE http://localhost:3003/api/blogs/65455a470f8895c795927df8 HTTP/1.1

###
PUT http://localhost:3003/api/blogs/65455de6577f7bbf18f51222 HTTP/1.1
Content-Type: application/json

{
  "likes": 100
}

### Users Get Request
GET http://localhost:3003/api/users/ HTTP/1.1

### Create a new user
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "garrix",
    "name": "garrix",
    "password": "garrix"
}

### Login
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "garrix",
    "password": "garrix"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhcnJpeCIsImlkIjoiNjU0OTc4ZGI4NDk0ZGQ2ZTMyNTI2NTY2IiwiaWF0IjoxNjk5MzE0MzcxfQ.13H6xBW-vxsSFhQUdLNpgh1eCPVEeurUTNYIT35K6xY

{
  "title": "first post",
  "author": "tej",
  "url": "blog/1",
  "likes": "100"
}