# fly.toml app configuration file generated for proud-hill-4181 on 2023-10-20T14:50:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-hill-4181"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
